// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxVAr87C8-FbFloj9Ly4ABzzKCaCF-Jj0',
    appId: '1:1010637977166:web:93008f9f79ce538e78751f',
    messagingSenderId: '1010637977166',
    projectId: 'eos-advanced-908cf',
    authDomain: 'eos-advanced-908cf.firebaseapp.com',
    storageBucket: 'eos-advanced-908cf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFebLL7m_g_uuhR9v8EChxDt_F_M9tZMo',
    appId: '1:1010637977166:android:dbf158cc266e55af78751f',
    messagingSenderId: '1010637977166',
    projectId: 'eos-advanced-908cf',
    storageBucket: 'eos-advanced-908cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZnPXYq3EoijTdXRMy3cniGi2XO2BDon0',
    appId: '1:1010637977166:ios:f99a537f62c887b578751f',
    messagingSenderId: '1010637977166',
    projectId: 'eos-advanced-908cf',
    storageBucket: 'eos-advanced-908cf.firebasestorage.app',
    iosClientId: '1010637977166-ritvgitu68r6cggs00v2sikc05euajf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eosAdvanceLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZnPXYq3EoijTdXRMy3cniGi2XO2BDon0',
    appId: '1:1010637977166:ios:f99a537f62c887b578751f',
    messagingSenderId: '1010637977166',
    projectId: 'eos-advanced-908cf',
    storageBucket: 'eos-advanced-908cf.firebasestorage.app',
    iosClientId: '1010637977166-ritvgitu68r6cggs00v2sikc05euajf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eosAdvanceLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxVAr87C8-FbFloj9Ly4ABzzKCaCF-Jj0',
    appId: '1:1010637977166:web:432bf69e48cb383b78751f',
    messagingSenderId: '1010637977166',
    projectId: 'eos-advanced-908cf',
    authDomain: 'eos-advanced-908cf.firebaseapp.com',
    storageBucket: 'eos-advanced-908cf.firebasestorage.app',
  );

}